title:              Tech Journal
email:              migueltrinidad1999@gmail.com
description:        Test update and deploy Discover the world of tech with me! This is my space to share short and sweet articles about random tech stuff. Let's explore together!
baseurl:            "/miguel_blog"
url:                "https://startbootstrap.github.io"

# Social Profiles
twitter_username:   migoy
github_username:    migoy99
facebook_username:  migoooooy
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
